<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Wfo;

class WfoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $wfos = [
            [
                "abbr" => "NCF",
                "fullname" => "NCEP",
                "state" => "MD",
                "tz" => "E",
                "url" => "https://www.weather.gov/ncep",
                "rid" => "ncf",
            ],
            [
                "abbr" => "AAQ",
                "fullname" => "PALMER",
                "state" => "AK",
                "tz" => "A",
                "url" => "https://www.tsunami.gov",
                "rid" => "aaq",
            ],
            [
                "abbr" => "ABQ",
                "fullname" => "ALBUQUERQUE",
                "state" => "NM",
                "tz" => "M",
                "url" => "http://www.srh.noaa.gov/abq",
                "rid" => "abx",
            ],
            [
                "abbr" => "ABR",
                "fullname" => "ABERDEEN",
                "state" => "SD",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/abr",
                "rid" => "abr",
            ],
            [
                "abbr" => "AFC",
                "fullname" => "ANCHORAGE",
                "state" => "AK",
                "tz" => "A",
                "url" => "http://pafc.arh.noaa.gov/",
                "rid" => "ahg",
            ],
            [
                "abbr" => "AFG",
                "fullname" => "FAIRBANKS",
                "state" => "AK",
                "tz" => "A",
                "url" => "http://pafg.arh.noaa.gov/",
                "rid" => "apd",
            ],
            [
                "abbr" => "AJK",
                "fullname" => "JUNEAU",
                "state" => "AK",
                "tz" => "A",
                "url" => "http://pajk.arh.noaa.gov/",
                "rid" => "acg",
            ],
            [
                "abbr" => "AKQ",
                "fullname" => "NORFOLK",
                "state" => "VA",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/akq",
                "rid" => "akq",
            ],
            [
                "abbr" => "ALY",
                "fullname" => "ALBANY",
                "state" => "NY",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/aly",
                "rid" => "enx",
            ],
            [
                "abbr" => "AMA",
                "fullname" => "AMARILLO",
                "state" => "TX",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/ama",
                "rid" => "ama",
            ],
            [
                "abbr" => "APX",
                "fullname" => "GAYLORD",
                "state" => "MI",
                "tz" => "E",
                "url" => "http://www.crh.noaa.gov/apx",
                "rid" => "apx",
            ],
            [
                "abbr" => "ARX",
                "fullname" => "LA CROSSE",
                "state" => "WI",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/arx",
                "rid" => "arx",
            ],
            [
                "abbr" => "BGM",
                "fullname" => "BINGHAMTON",
                "state" => "NY",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/bgm",
                "rid" => "bgm",
            ],
            [
                "abbr" => "BIS",
                "fullname" => "BISMARCK",
                "state" => "ND",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/bis",
                "rid" => "bis",
            ],
            [
                "abbr" => "BMX",
                "fullname" => "BIRMINGHAM",
                "state" => "AL",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/bmx",
                "rid" => "bmx",
            ],
            [
                "abbr" => "BOI",
                "fullname" => "BOISE",
                "state" => "ID",
                "tz" => "M",
                "url" => "http://www.wrh.noaa.gov/boi",
                "rid" => "cbx",
            ],
            [
                "abbr" => "BOU",
                "fullname" => "BOULDER",
                "state" => "CO",
                "tz" => "M",
                "url" => "http://www.crh.noaa.gov/bou",
                "rid" => "ftg",
            ],
            [
                "abbr" => "BOX",
                "fullname" => "BOSTON",
                "state" => "MA",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/box",
                "rid" => "box",
            ],
            [
                "abbr" => "BRO",
                "fullname" => "BROWNSVILLE",
                "state" => "TX",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/bro",
                "rid" => "bro",
            ],
            [
                "abbr" => "BTV",
                "fullname" => "BURLINGTON",
                "state" => "VT",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/btv",
                "rid" => "cxx",
            ],
            [
                "abbr" => "BUF",
                "fullname" => "BUFFALO",
                "state" => "NY",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/buf",
                "rid" => "buf",
            ],
            [
                "abbr" => "BYZ",
                "fullname" => "BILLINGS",
                "state" => "MT",
                "tz" => "M",
                "url" => "http://www.wrh.noaa.gov/byz",
                "rid" => "blx",
            ],
            [
                "abbr" => "CAE",
                "fullname" => "COLUMBIA",
                "state" => "SC",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/cae",
                "rid" => "cae",
            ],
            [
                "abbr" => "CAR",
                "fullname" => "CARIBOU",
                "state" => "ME",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/car",
                "rid" => "cbw",
            ],
            [
                "abbr" => "CHS",
                "fullname" => "CHARLESTON",
                "state" => "SC",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/chs",
                "rid" => "clx",
            ],
            [
                "abbr" => "CLE",
                "fullname" => "CLEVELAND",
                "state" => "OH",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/cle",
                "rid" => "cle",
            ],
            [
                "abbr" => "CRP",
                "fullname" => "CORPUS CHRISTI",
                "state" => "TX",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/crp",
                "rid" => "crp",
            ],
            [
                "abbr" => "CTP",
                "fullname" => "STATE COLLEGE",
                "state" => "PA",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/ctp",
                "rid" => "ccx",
            ],
            [
                "abbr" => "CYS",
                "fullname" => "CHEYENNE",
                "state" => "WY",
                "tz" => "M",
                "url" => "http://www.crh.noaa.gov/cys",
                "rid" => "cys",
            ],
            [
                "abbr" => "DDC",
                "fullname" => "DODGE CITY",
                "state" => "KS",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/ddc",
                "rid" => "ddc",
            ],
            [
                "abbr" => "DLH",
                "fullname" => "DULUTH",
                "state" => "MN",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/dlh",
                "rid" => "dlh",
            ],
            [
                "abbr" => "DMX",
                "fullname" => "DES MOINES",
                "state" => "IA",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/dmx",
                "rid" => "dmx",
            ],
            [
                "abbr" => "DTX",
                "fullname" => "DETROIT / PONTIAC",
                "state" => "MI",
                "tz" => "E",
                "url" => "http://www.crh.noaa.gov/dtx",
                "rid" => "dtx",
            ],
            [
                "abbr" => "DVN",
                "fullname" => "DAVENPORT / QUAD CITIES",
                "state" => "IA",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/dvn",
                "rid" => "dvn",
            ],
            [
                "abbr" => "EAX",
                "fullname" => "PLEASANT HILL / KANSAS CITY",
                "state" => "MO",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/eax",
                "rid" => "eax",
            ],
            [
                "abbr" => "EKA",
                "fullname" => "EUREKA",
                "state" => "CA",
                "tz" => "P",
                "url" => "http://www.wrh.noaa.gov/eka",
                "rid" => "bhx",
            ],
            [
                "abbr" => "EPZ",
                "fullname" => "SANTA TERESA",
                "state" => "NM",
                "tz" => "M",
                "url" => "http://www.srh.noaa.gov/epz",
                "rid" => "epz",
            ],
            [
                "abbr" => "EWX",
                "fullname" => "NEW BRAUNFELS",
                "state" => "TX",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/ewx",
                "rid" => "ewx",
            ],
            [
                "abbr" => "FFC",
                "fullname" => "PEACHTREE CITY",
                "state" => "GA",
                "tz" => "E",
                "url" => "http://www.srh.noaa.gov/ffc",
                "rid" => "ffc",
            ],
            [
                "abbr" => "FGF",
                "fullname" => "FARGO / GRAND FORKS",
                "state" => "ND",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/fgf",
                "rid" => "mvx",
            ],
            [
                "abbr" => "FGZ",
                "fullname" => "FLAGSTAFF",
                "state" => "AZ",
                "tz" => "M",
                "url" => "http://www.wrh.noaa.gov/fgz",
                "rid" => "fsx",
            ],
            [
                "abbr" => "FSD",
                "fullname" => "SIOUX FALLS",
                "state" => "SD",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/fsd",
                "rid" => "fsd",
            ],
            [
                "abbr" => "FWD",
                "fullname" => "FORT WORTH",
                "state" => "TX",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/fwd",
                "rid" => "fws",
            ],
            [
                "abbr" => "GGW",
                "fullname" => "GLASGOW",
                "state" => "MT",
                "tz" => "M",
                "url" => "http://www.wrh.noaa.gov/ggw",
                "rid" => "ggw",
            ],
            [
                "abbr" => "GID",
                "fullname" => "GRAND ISLAND",
                "state" => "NE",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/gid",
                "rid" => "uex",
            ],
            [
                "abbr" => "GJT",
                "fullname" => "GRAND JUNCTION",
                "state" => "CO",
                "tz" => "M",
                "url" => "http://www.crh.noaa.gov/gjt",
                "rid" => "gjx",
            ],
            [
                "abbr" => "GLD",
                "fullname" => "GOODLAND",
                "state" => "KS",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/gld",
                "rid" => "gld",
            ],
            [
                "abbr" => "GRB",
                "fullname" => "ASHWAUBENON",
                "state" => "WI",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/grb",
                "rid" => "grb",
            ],
            [
                "abbr" => "GRR",
                "fullname" => "GRAND RAPIDS",
                "state" => "MI",
                "tz" => "E",
                "url" => "http://www.crh.noaa.gov/grr",
                "rid" => "grr",
            ],
            [
                "abbr" => "GSP",
                "fullname" => "GREER / SPARTANSBURG",
                "state" => "SC",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/gsp",
                "rid" => "gsp",
            ],
            [
                "abbr" => "GYX",
                "fullname" => "PORTLAND",
                "state" => "ME",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/gyx",
                "rid" => "gyx",
            ],
            [
                "abbr" => "GUM",
                "fullname" => "TYAN",
                "state" => "GU",
                "tz" => "G",
                "url" => "http://www.prh.noaa.gov/guam/",
                "rid" => "gum",
            ],
            [
                "abbr" => "HEB",
                "fullname" => "EWA BEACH",
                "state" => "HI",
                "tz" => "H",
                "url" => "https://www.tsunami.gov",
                "rid" => "heb",
            ],
            [
                "abbr" => "HFO",
                "fullname" => "HONOLULU",
                "state" => "HI",
                "tz" => "H",
                "url" => "http://www.prh.noaa.gov/pr/hnl/",
                "rid" => "hmo",
            ],
            [
                "abbr" => "HGX",
                "fullname" => "HOUSTON / DICKINSON",
                "state" => "TX",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/hgx",
                "rid" => "hgx",
            ],
            [
                "abbr" => "HNX",
                "fullname" => "HANFORD / SAN JOAQUIN VALLEY",
                "state" => "CA",
                "tz" => "P",
                "url" => "http://www.srh.noaa.gov/hnx",
                "rid" => "hnx",
            ],
            [
                "abbr" => "HUN",
                "fullname" => "HUNTSVILLE",
                "state" => "AL",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/hun",
                "rid" => "htx",
            ],
            [
                "abbr" => "ICT",
                "fullname" => "WICHITA",
                "state" => "KS",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/ict",
                "rid" => "ict",
            ],
            [
                "abbr" => "ILM",
                "fullname" => "WILMINGTON",
                "state" => "NC",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/ilm",
                "rid" => "ltx",
            ],
            [
                "abbr" => "ILN",
                "fullname" => "WILMINGTON",
                "state" => "OH",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/iln",
                "rid" => "iln",
            ],
            [
                "abbr" => "ILX",
                "fullname" => "LINCOLN",
                "state" => "IL",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/ilx",
                "rid" => "ilx",
            ],
            [
                "abbr" => "IND",
                "fullname" => "INDIANAPOLIS",
                "state" => "IN",
                "tz" => "E",
                "url" => "http://www.crh.noaa.gov/ind",
                "rid" => "ind",
            ],
            [
                "abbr" => "IWX",
                "fullname" => "NORTH WEBSTER",
                "state" => "IN",
                "tz" => "E",
                "url" => "http://www.crh.noaa.gov/iwx",
                "rid" => "iwx",
            ],
            [
                "abbr" => "JAN",
                "fullname" => "JACKSON",
                "state" => "MS",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/jan",
                "rid" => "dgx",
            ],
            [
                "abbr" => "JAX",
                "fullname" => "JACKSONVILLE",
                "state" => "FL",
                "tz" => "E",
                "url" => "http://www.srh.noaa.gov/jax",
                "rid" => "jax",
            ],
            [
                "abbr" => "JKL",
                "fullname" => "JACKSON",
                "state" => "KY",
                "tz" => "E",
                "url" => "http://www.crh.noaa.gov/jkl",
                "rid" => "jkl",
            ],
            [
                "abbr" => "JSJ",
                "fullname" => "SAN JUAN",
                "state" => "PR",
                "tz" => "E",
                "url" => "http://www.srh.noaa.gov/sju",
                "rid" => "jua",
            ],
            [
                "abbr" => "KEY",
                "fullname" => "KEY WEST",
                "state" => "FL",
                "tz" => "E",
                "url" => "http://www.srh.noaa.gov/key",
                "rid" => "byx",
            ],
            [
                "abbr" => "LBF",
                "fullname" => "NORTH PLATTE",
                "state" => "NE",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/lbf",
                "rid" => "lnx",
            ],
            [
                "abbr" => "LCH",
                "fullname" => "LAKE CHARLES",
                "state" => "LA",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/lch",
                "rid" => "lch",
            ],
            [
                "abbr" => "LIX",
                "fullname" => "SLIDELL",
                "state" => "LA",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/lix",
                "rid" => "lix",
            ],
            [
                "abbr" => "LKN",
                "fullname" => "ELKO",
                "state" => "NV",
                "tz" => "P",
                "url" => "http://www.wrh.noaa.gov/lkn",
                "rid" => "lrx",
            ],
            [
                "abbr" => "LMK",
                "fullname" => "LOUISVILLE",
                "state" => "KY",
                "tz" => "E",
                "url" => "http://www.crh.noaa.gov/lmk",
                "rid" => "lvx",
            ],
            [
                "abbr" => "LOT",
                "fullname" => "CHICAGO",
                "state" => "IL",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/lot",
                "rid" => "lot",
            ],
            [
                "abbr" => "LOX",
                "fullname" => "LOS ANGELES",
                "state" => "CA",
                "tz" => "P",
                "url" => "http://www.srh.noaa.gov/lox",
                "rid" => "lix",
            ],
            [
                "abbr" => "LSX",
                "fullname" => "ST LOUIS",
                "state" => "MO",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/lsx",
                "rid" => "lsx",
            ],
            [
                "abbr" => "LUB",
                "fullname" => "LUBBOCK",
                "state" => "TX",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/lub",
                "rid" => "lbb",
            ],
            [
                "abbr" => "LWX",
                "fullname" => "STERLING",
                "state" => "VA",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/lwx",
                "rid" => "lwx",
            ],
            [
                "abbr" => "LZK",
                "fullname" => "LITTLE ROCK",
                "state" => "AR",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/lzk",
                "rid" => "lzk",
            ],
            [
                "abbr" => "MAF",
                "fullname" => "MIDLAND",
                "state" => "TX",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/maf",
                "rid" => "maf",
            ],
            [
                "abbr" => "MEG",
                "fullname" => "MEMPHIS",
                "state" => "TN",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/meg",
                "rid" => "nqa",
            ],
            [
                "abbr" => "MFL",
                "fullname" => "MIAMI",
                "state" => "FL",
                "tz" => "E",
                "url" => "http://www.srh.noaa.gov/mfl",
                "rid" => "amx",
            ],
            [
                "abbr" => "MFR",
                "fullname" => "MEDFORD",
                "state" => "OR",
                "tz" => "P",
                "url" => "http://www.srh.noaa.gov/mfr",
                "rid" => "amx",
            ],
            [
                "abbr" => "MHX",
                "fullname" => "MOREHEAD CITY / NEWPORT",
                "state" => "NC",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/mhx",
                "rid" => "mhx",
            ],
            [
                "abbr" => "MKX",
                "fullname" => "MILWAUKEE",
                "state" => "WI",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/mkx",
                "rid" => "mkx",
            ],
            [
                "abbr" => "MLB",
                "fullname" => "MELBOURNE",
                "state" => "FL",
                "tz" => "E",
                "url" => "http://www.srh.noaa.gov/mlb",
                "rid" => "mlb",
            ],
            [
                "abbr" => "MOB",
                "fullname" => "MOBILE / PENSACOLA",
                "state" => "AL",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/mob",
                "rid" => "mob",
            ],
            [
                "abbr" => "MPX",
                "fullname" => "TWIN CITIES",
                "state" => "MN",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/mpx",
                "rid" => "mpx",
            ],
            [
                "abbr" => "MQT",
                "fullname" => "MARQUETTE",
                "state" => "MI",
                "tz" => "E",
                "url" => "http://www.crh.noaa.gov/mqt",
                "rid" => "mqt",
            ],
            [
                "abbr" => "MRX",
                "fullname" => "MORRISTOWN",
                "state" => "TN",
                "tz" => "E",
                "url" => "http://www.srh.noaa.gov/mrx",
                "rid" => "mrx",
            ],
            [
                "abbr" => "MSO",
                "fullname" => "MISSOULA",
                "state" => "MT",
                "tz" => "M",
                "url" => "http://www.wrh.noaa.gov/mso",
                "rid" => "msx",
            ],
            [
                "abbr" => "MTR",
                "fullname" => "SAN FRANCISCO BAY AREA",
                "state" => "CA",
                "tz" => "P",
                "url" => "http://www.wrh.noaa.gov/mtr",
                "rid" => "mux",
            ],
            [
                "abbr" => "OAX",
                "fullname" => "OMAHA/VALLEY",
                "state" => "NE",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/oax",
                "rid" => "oax",
            ],
            [
                "abbr" => "OHX",
                "fullname" => "NASHVILLE",
                "state" => "TN",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/ohx",
                "rid" => "ohx",
            ],
            [
                "abbr" => "OKX",
                "fullname" => "UPTON / NEW YORK CITY",
                "state" => "NY",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/okx",
                "rid" => "okx",
            ],
            [
                "abbr" => "OTX",
                "fullname" => "SPOKANE",
                "state" => "WA",
                "tz" => "P",
                "url" => "http://www.srh.noaa.gov/otx",
                "rid" => "ohx",
            ],
            [
                "abbr" => "OUN",
                "fullname" => "NORMAN",
                "state" => "OK",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/oun",
                "rid" => "tlx",
            ],
            [
                "abbr" => "PAH",
                "fullname" => "PADUCAH",
                "state" => "KY",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/pah",
                "rid" => "pah",
            ],
            [
                "abbr" => "PBZ",
                "fullname" => "PITTSBURGH",
                "state" => "PA",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/pbz",
                "rid" => "pbz",
            ],
            [
                "abbr" => "PDT",
                "fullname" => "PENDLETON",
                "state" => "OR",
                "tz" => "P",
                "url" => "http://www.wrh.noaa.gov/pdt",
                "rid" => "pdt",
            ],
            [
                "abbr" => "PHI",
                "fullname" => "MT HOLLY / PHILADELPHIA",
                "state" => "PA",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/phi",
                "rid" => "dix",
            ],
            [
                "abbr" => "PIH",
                "fullname" => "POCATELLO",
                "state" => "ID",
                "tz" => "M",
                "url" => "http://www.wrh.noaa.gov/pih",
                "rid" => "sfx",
            ],
            [
                "abbr" => "PQR",
                "fullname" => "PORTLAND",
                "state" => "OR",
                "tz" => "P",
                "url" => "http://www.wrh.noaa.gov/pqr",
                "rid" => "rtx",
            ],
            [
                "abbr" => "PSR",
                "fullname" => "PHOENIX",
                "state" => "AZ",
                "tz" => "M",
                "url" => "http://www.wrh.noaa.gov/psr",
                "rid" => "iwa",
            ],
            [
                "abbr" => "PUB",
                "fullname" => "PUEBLO",
                "state" => "CO",
                "tz" => "M",
                "url" => "http://www.crh.noaa.gov/pub",
                "rid" => "pux",
            ],
            [
                "abbr" => "RAH",
                "fullname" => "RALEIGH",
                "state" => "NC",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/rah",
                "rid" => "rax",
            ],
            [
                "abbr" => "REV",
                "fullname" => "RENO",
                "state" => "NV",
                "tz" => "P",
                "url" => "http://www.wrh.noaa.gov/rev",
                "rid" => "rgx",
            ],
            [
                "abbr" => "RIW",
                "fullname" => "RIVERTON",
                "state" => "WY",
                "tz" => "M",
                "url" => "http://www.crh.noaa.gov/riw",
                "rid" => "riw",
            ],
            [
                "abbr" => "RLX",
                "fullname" => "CHARLESTON",
                "state" => "WV",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/rlx",
                "rid" => "rlx",
            ],
            [
                "abbr" => "RNK",
                "fullname" => "BLACKSBURG",
                "state" => "VA",
                "tz" => "E",
                "url" => "http://www.erh.noaa.gov/er/rnk",
                "rid" => "fcx",
            ],
            [
                "abbr" => "SDM",
                "fullname" => "COLLEGE PARK",
                "state" => "MD",
                "tz" => "E",
                "url" => "https://www.nco.ncep.noaa.gov",
                "rid" => "sdm",
            ],
            [
                "abbr" => "SEW",
                "fullname" => "SEATTLE",
                "state" => "WA",
                "tz" => "P",
                "url" => "http://www.wrh.noaa.gov/sew",
                "rid" => "atx",
            ],
            [
                "abbr" => "SGF",
                "fullname" => "SPRINGFIELD",
                "state" => "MO",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/sgf",
                "rid" => "sgf",
            ],
            [
                "abbr" => "SGX",
                "fullname" => "SAN DIEGO",
                "state" => "CA",
                "tz" => "P",
                "url" => "http://www.srh.noaa.gov/sgx",
                "rid" => "sox",
            ],
            [
                "abbr" => "SHV",
                "fullname" => "SHREVEPORT",
                "state" => "LA",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/shv",
                "rid" => "shv",
            ],
            [
                "abbr" => "SJT",
                "fullname" => "SAN ANGELO",
                "state" => "TX",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/sjt",
                "rid" => "dyx",
            ],
            [
                "abbr" => "SLC",
                "fullname" => "SALT LAKE CITY",
                "state" => "UT",
                "tz" => "M",
                "url" => "http://www.wrh.noaa.gov/slc",
                "rid" => "mtx",
            ],
            [
                "abbr" => "STO",
                "fullname" => "SACRAMENTO",
                "state" => "CA",
                "tz" => "P",
                "url" => "http://www.wrh.noaa.gov/sto",
                "rid" => "dax",
            ],
            [
                "abbr" => "TAE",
                "fullname" => "TALLAHASSEE",
                "state" => "FL",
                "tz" => "E",
                "url" => "http://www.srh.noaa.gov/tae",
                "rid" => "tlh",
            ],
            [
                "abbr" => "TBW",
                "fullname" => "TAMPA BAY",
                "state" => "FL",
                "tz" => "E",
                "url" => "http://www.srh.noaa.gov/tbw",
                "rid" => "tbw",
            ],
            [
                "abbr" => "TFX",
                "fullname" => "GREAT FALLS",
                "state" => "MT",
                "tz" => "M",
                "url" => "http://www.wrh.noaa.gov/tfx",
                "rid" => "tfx",
            ],
            [
                "abbr" => "TOP",
                "fullname" => "TOPEKA",
                "state" => "KS",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/top",
                "rid" => "twx",
            ],
            [
                "abbr" => "TSA",
                "fullname" => "TULSA",
                "state" => "OK",
                "tz" => "C",
                "url" => "http://www.srh.noaa.gov/tsa",
                "rid" => "inx",
            ],
            [
                "abbr" => "TWC",
                "fullname" => "TUCSON",
                "state" => "AZ",
                "tz" => "M",
                "url" => "http://www.wrh.noaa.gov/twc",
                "rid" => "emx",
            ],
            [
                "abbr" => "UNR",
                "fullname" => "RAPID CITY",
                "state" => "SD",
                "tz" => "C",
                "url" => "http://www.crh.noaa.gov/unr",
                "rid" => "udx",
            ],
            [
                "abbr" => "VEF",
                "fullname" => "LAS VEGAS",
                "state" => "NV",
                "tz" => "P",
                "url" => "http://www.wrh.noaa.gov/vef",
                "rid" => "esx",
            ],
            [
                "abbr" => "WNS",
                "fullname" => "NORMAN",
                "state" => "OK",
                "tz" => "C",
                "url" => "http://www.spc.noaa.gov",
                "rid" => "spc",
            ],
        ];

        print "Preparing to seed 'wfos' table with " . count($wfos) . " values..\n";
        for($i=0; $i<count($wfos); $i++) {
            if (DB::table('wfos')->where('fullname', '=', $wfos[$i]['fullname'])->count() === 0) {
                DB::table('wfos')->insert($wfos[$i]);
                print 'Data for "' . $wfos[$i]['fullname'] . '" added to database.' . "\n";
            } else {
                print 'Data for "' . $wfos[$i]['fullname'] . '" already exists, skipping..' . "\n";
            }
        }
    }

}
